### ISSUE TITLE
Greece appears 2 times in Cases by country sheet

### ISSUE THREAD

**Issue by theonikl** [globaldothealth/monkeypox#108] opened 2022-06-25 00:06 UTC
![image](https://user-images.githubusercontent.com/108159207/175750046-c11b79ef-6ab1-4f5d-a8b2-0ca4ec61de5b.png)

**Comment by corneliusroemer** [comment] 2022-06-26 15:02
Root cause is that in row 3981 the country has a whitespace appended, like `Greece ` and the other Greeces are `Greece`

This could be fixed in the future by stripping terminal whitespace.

<img width="802" alt="image" src="https://user-images.githubusercontent.com/25161793/175820527-f49551bb-60f9-4bf0-b4a0-eb625f989d48.png">

**Comment by corneliusroemer** [comment] 2022-06-26 15:05
Seems to be fixed now :)

**Closed** 2022-06-26 15:15 UTC
